In [1]:
import pandas as pd

In [11]:
# importing draft data
draft_2021 = pd.read_csv('draft_data/2021.csv')
draft_2020 = pd.read_csv('draft_data/2020.csv')
draft_2019 = pd.read_csv('draft_data/2019.csv')
draft_2018 = pd.read_csv('draft_data/2018.csv')
draft_2017 = pd.read_csv('draft_data/2017.csv')
draft_2016 = pd.read_csv('draft_data/2016.csv')
draft_2015 = pd.read_csv('draft_data/2015.csv')
draft_2014 = pd.read_csv('draft_data/2014.csv')
draft_2013 = pd.read_csv('draft_data/2013.csv')
draft_2012 = pd.read_csv('draft_data/2012.csv')
draft_2011 = pd.read_csv('draft_data/2011.csv')
draft_2010 = pd.read_csv('draft_data/2010.csv')
draft_2009 = pd.read_csv('draft_data/2009.csv')
draft_2008 = pd.read_csv('draft_data/2008.csv')
draft_2007 = pd.read_csv('draft_data/2007.csv')
draft_2006 = pd.read_csv('draft_data/2006.csv')
draft_2005 = pd.read_csv('draft_data/2005.csv')
draft_2004 = pd.read_csv('draft_data/2004.csv')
draft_2003 = pd.read_csv('draft_data/2003.csv')
draft_2002 = pd.read_csv('draft_data/2002.csv')
draft_2001 = pd.read_csv('draft_data/2001.csv')
draft_2000 = pd.read_csv('draft_data/2000.csv')
draft_1999 = pd.read_csv('draft_data/1999.csv')
draft_1998 = pd.read_csv('draft_data/1998.csv')
draft_1997 = pd.read_csv('draft_data/1997.csv')
draft_1996 = pd.read_csv('draft_data/1996.csv')
draft_1995 = pd.read_csv('draft_data/1995.csv')
draft_1994 = pd.read_csv('draft_data/1994.csv')
draft_1993 = pd.read_csv('draft_data/1993.csv')

In [13]:
# read in combine data
combine_2021 = pd.read_csv('combine_results/2021.csv')
combine_2020 = pd.read_csv('combine_results/2020.csv')
combine_2019 = pd.read_csv('combine_results/2019.csv')
combine_2018 = pd.read_csv('combine_results/2018.csv')
combine_2017 = pd.read_csv('combine_results/2017.csv')
combine_2016 = pd.read_csv('combine_results/2016.csv')
combine_2015 = pd.read_csv('combine_results/2015.csv')
combine_2014 = pd.read_csv('combine_results/2014.csv')
combine_2013 = pd.read_csv('combine_results/2013.csv')
combine_2012 = pd.read_csv('combine_results/2012.csv')
combine_2011 = pd.read_csv('combine_results/2011.csv')
combine_2010 = pd.read_csv('combine_results/2010.csv')
combine_2009 = pd.read_csv('combine_results/2009.csv')
combine_2008 = pd.read_csv('combine_results/2008.csv')
combine_2007 = pd.read_csv('combine_results/2007.csv')
combine_2006 = pd.read_csv('combine_results/2006.csv')
combine_2005 = pd.read_csv('combine_results/2005.csv')
combine_2004 = pd.read_csv('combine_results/2004.csv')
combine_2003 = pd.read_csv('combine_results/2003.csv')
combine_2002 = pd.read_csv('combine_results/2002.csv')
combine_2001 = pd.read_csv('combine_results/2001.csv')
combine_2000 = pd.read_csv('combine_results/2000.csv')
combine_1999 = pd.read_csv('combine_results/1999.csv')
combine_1998 = pd.read_csv('combine_results/1998.csv')
combine_1997 = pd.read_csv('combine_results/1997.csv')
combine_1996 = pd.read_csv('combine_results/1996.csv')
combine_1995 = pd.read_csv('combine_results/1995.csv')
combine_1994 = pd.read_csv('combine_results/1994.csv')
combine_1993 = pd.read_csv('combine_results/1993.csv')

In [15]:
# read in passing data
passing_2021 = pd.read_csv('passing/2021.csv')
passing_2020 = pd.read_csv('passing/2020.csv')
passing_2019 = pd.read_csv('passing/2019.csv')
passing_2018 = pd.read_csv('passing/2018.csv')
passing_2017 = pd.read_csv('passing/2017.csv')
passing_2016 = pd.read_csv('passing/2016.csv')
passing_2015 = pd.read_csv('passing/2015.csv')
passing_2014 = pd.read_csv('passing/2014.csv')
passing_2013 = pd.read_csv('passing/2013.csv')
passing_2012 = pd.read_csv('passing/2012.csv')
passing_2011 = pd.read_csv('passing/2011.csv')
passing_2010 = pd.read_csv('passing/2010.csv')
passing_2009 = pd.read_csv('passing/2009.csv')
passing_2008 = pd.read_csv('passing/2008.csv')
passing_2007 = pd.read_csv('passing/2007.csv')
passing_2006 = pd.read_csv('passing/2006.csv')
passing_2005 = pd.read_csv('passing/2005.csv')
passing_2004 = pd.read_csv('passing/2004.csv')
passing_2003 = pd.read_csv('passing/2003.csv')
passing_2002 = pd.read_csv('passing/2002.csv')
passing_2001 = pd.read_csv('passing/2001.csv')
passing_2000 = pd.read_csv('passing/2000.csv')
passing_1999 = pd.read_csv('passing/1999.csv')
passing_1998 = pd.read_csv('passing/1998.csv')
passing_1997 = pd.read_csv('passing/1997.csv')
passing_1996 = pd.read_csv('passing/1996.csv')
passing_1995 = pd.read_csv('passing/1995.csv')
passing_1994 = pd.read_csv('passing/1994.csv')
passing_1993 = pd.read_csv('passing/1993.csv')

In [16]:
# read in receiving data
receiving_2021 = pd.read_csv('receiving/2021.csv')
receiving_2020 = pd.read_csv('receiving/2020.csv')
receiving_2019 = pd.read_csv('receiving/2019.csv')
receiving_2018 = pd.read_csv('receiving/2018.csv')
receiving_2017 = pd.read_csv('receiving/2017.csv')
receiving_2016 = pd.read_csv('receiving/2016.csv')
receiving_2015 = pd.read_csv('receiving/2015.csv')
receiving_2014 = pd.read_csv('receiving/2014.csv')
receiving_2013 = pd.read_csv('receiving/2013.csv')
receiving_2012 = pd.read_csv('receiving/2012.csv')
receiving_2011 = pd.read_csv('receiving/2011.csv')
receiving_2010 = pd.read_csv('receiving/2010.csv')
receiving_2009 = pd.read_csv('receiving/2009.csv')
receiving_2008 = pd.read_csv('receiving/2008.csv')
receiving_2007 = pd.read_csv('receiving/2007.csv')
receiving_2006 = pd.read_csv('receiving/2006.csv')
receiving_2005 = pd.read_csv('receiving/2005.csv')
receiving_2004 = pd.read_csv('receiving/2004.csv')
receiving_2003 = pd.read_csv('receiving/2003.csv')
receiving_2002 = pd.read_csv('receiving/2002.csv')
receiving_2001 = pd.read_csv('receiving/2001.csv')
receiving_2000 = pd.read_csv('receiving/2000.csv')
receiving_1999 = pd.read_csv('receiving/1999.csv')
receiving_1998 = pd.read_csv('receiving/1998.csv')
receiving_1997 = pd.read_csv('receiving/1997.csv')
receiving_1996 = pd.read_csv('receiving/1996.csv')
receiving_1995 = pd.read_csv('receiving/1995.csv')
receiving_1994 = pd.read_csv('receiving/1994.csv')
receiving_1993 = pd.read_csv('receiving/1993.csv')

In [17]:
# get rushing data
rushing_2021 = pd.read_csv('rushing/2021.csv')
rushing_2020 = pd.read_csv('rushing/2020.csv')
rushing_2019 = pd.read_csv('rushing/2019.csv')
rushing_2018 = pd.read_csv('rushing/2018.csv')
rushing_2017 = pd.read_csv('rushing/2017.csv')
rushing_2016 = pd.read_csv('rushing/2016.csv')
rushing_2015 = pd.read_csv('rushing/2015.csv')
rushing_2014 = pd.read_csv('rushing/2014.csv')
rushing_2013 = pd.read_csv('rushing/2013.csv')
rushing_2012 = pd.read_csv('rushing/2012.csv')
rushing_2011 = pd.read_csv('rushing/2011.csv')
rushing_2010 = pd.read_csv('rushing/2010.csv')
rushing_2009 = pd.read_csv('rushing/2009.csv')
rushing_2008 = pd.read_csv('rushing/2008.csv')
rushing_2007 = pd.read_csv('rushing/2007.csv')
rushing_2006 = pd.read_csv('rushing/2006.csv')
rushing_2005 = pd.read_csv('rushing/2005.csv')
rushing_2004 = pd.read_csv('rushing/2004.csv')
rushing_2003 = pd.read_csv('rushing/2003.csv')
rushing_2002 = pd.read_csv('rushing/2002.csv')
rushing_2001 = pd.read_csv('rushing/2001.csv')
rushing_2000 = pd.read_csv('rushing/2000.csv')
rushing_1999 = pd.read_csv('rushing/1999.csv')
rushing_1998 = pd.read_csv('rushing/1998.csv')
rushing_1997 = pd.read_csv('rushing/1997.csv')
rushing_1996 = pd.read_csv('rushing/1996.csv')
rushing_1995 = pd.read_csv('rushing/1995.csv')
rushing_1994 = pd.read_csv('rushing/1994.csv')
rushing_1993 = pd.read_csv('rushing/1993.csv')

In [18]:
rushing_1993.head()

,Rk,Player,School,Conf,G,RushAtt,RushYds,RushAvg,RushTD,Rec,RecYds,RecAvg,RecTD,Plays,TotalYds,YardsPerPlay,TotalTDs
0,1,Leeland McElroy,Texas A&M,SWC,11,72,613,8.5,7,19.0,224.0,11.8,4.0,91,837,9.2,11
1,2,Charlie Garner,Tennessee,SEC,11,159,1161,7.3,8,12.0,81.0,6.8,0.0,171,1242,7.3,8
2,3,Dorsey Levens,Georgia Tech,ACC,10,114,823,7.2,8,8.0,134.0,16.8,1.0,122,957,7.8,9
3,4,J.J. Young,Oregon State,Pac-10,11,136,955,7.0,8,4.0,32.0,8.0,1.0,140,987,7.1,9
4,5,Ki-Jana Carter,Penn State,Big Ten,11,155,1026,6.6,7,6.0,49.0,8.2,0.0,161,1075,6.7,7

In [19]:
draft_1993.head()

   Round  Pick Team           Player Position   Age          School
0      1     1  NWE     Drew Bledsoe       QB  21.0  Washington St.
1      1     2  SEA       Rick Mirer       QB  23.0      Notre Dame
2      1     3  PHO  Garrison Hearst       RB  22.0         Georgia
3      1     4  NYJ     Marvin Jones       LB  21.0     Florida St.
4      1     5  CIN    John Copeland       DE  22.0         Alabama

In [ ]:
def clean_draft_df(df):
    """Function to remove unwanted positions"""